---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sqldf)
library(readxl)
library(xlsx)
```

```{r}
og_mci = read_csv("Major_Crime_Indicators_Open_Data_6927126107499016617.csv")
og_mci
```

```{r}
# Writing out features onto an excel file so its easier to manually assess
# og_mci %>% distinct(LOCATION_TYPE) -> temp  # 54 values, may have to feature engineer this
# 
# sqldf("
#       SELECT OFFENCE, COUNT(OBJECTID) num_rows
#       FROM og_mci
#       GROUP BY OFFENCE
#       ") -> temp
# 
# write.xlsx(temp, "temp.xlsx")

location_type_rework = read_xlsx("feature_rework.xlsx", "LOCATION_TYPE")
ucr_code_rework = read_xlsx("feature_rework.xlsx", "UCR_CODE")
offence_rework = read_xlsx("feature_rework.xlsx", "OFFENCE")
month_rework = read_xlsx("feature_rework.xlsx", "MONTH")
day_rework = read_xlsx("feature_rework.xlsx", "DAY")
holidays = read_xlsx("feature_rework.xlsx", "HOLIDAYS")
```

Adding the features together

```{r}
sqldf("
      SELECT A.*, B.LOCATION_TYPE_REWORK, C.UCR_CODE_DESCRIPTION, C.UCR_CODE_CATEGORY, D.OFFENCE_REWORK,
             E.MONTH_NUM REPORT_MONTH_NUM, F.MONTH_NUM OCC_MONTH_NUM,
             G.DOW_NUM REPORT_DOW_NUM, H.DOW_NUM OCC_DOW_NUM,
             I.IS_HOLIDAY, I.HOLIDAY_DESCRIPTION
      FROM og_mci A LEFT JOIN location_type_rework B
      ON A.LOCATION_TYPE = B.LOCATION_TYPE
      LEFT JOIN ucr_code_rework C
      ON A.UCR_CODE = C.UCR_CODE
      LEFT JOIN offence_rework D
      ON A.OFFENCE = D.OFFENCE
      LEFT JOIN month_rework E
      ON A.REPORT_MONTH = E.MONTH
      LEFT JOIN month_rework F
      ON A.OCC_MONTH = F.MONTH
      LEFT JOIN day_rework G
      ON A.REPORT_DOW = G.DAY_OF_WEEK
      LEFT JOIN day_rework H
      ON A.OCC_DOW = H.DAY_OF_WEEK
      LEFT JOIN holidays I
      ON  A.OCC_YEAR = I.YEAR
      AND A.OCC_DAY = I.DAY
      AND F.MONTH_NUM = I.MONTH
      ") %>% 
   mutate(DOW_SIMPLE = ifelse(OCC_DOW_NUM < 5, "Weekday",
                              ifelse(OCC_DOW_NUM == 5, "Friday", "Weekend"))) -> non_agg_df
non_agg_df$IS_HOLIDAY[is.na(non_agg_df$IS_HOLIDAY)] <- "N"
non_agg_df$HOLIDAY_DESCRIPTION[is.na(non_agg_df$HOLIDAY_DESCRIPTION)] <- "None"
non_agg_df
```
Variables:
* OCC_YEAR
* OCC_MONTH
* OCC_DAY
* OCC_HOUR
* OCC_DOW
* DIVISION
* PREMISES_TYPE
* UCR_CODE_CATEGORY
* OFFENCE_REWORK
* NEIGHBOURHOOD_158
* IS_HOLIDAY
* HOLIDAY_DESCRIPTION
* DOW_SIMPLE

* MCI_CATEGORY




```{r}
non_agg_df %>%
   filter(OCC_YEAR >= 2018 & OCC_YEAR <= 2023) %>% 
   select(EVENT_UNIQUE_ID, OCC_YEAR, OCC_MONTH_NUM, OCC_DAY, OCC_HOUR, OCC_DOY, OCC_DOW,
          DIVISION, PREMISES_TYPE, UCR_CODE_CATEGORY, OFFENCE_REWORK,
          NEIGHBOURHOOD_158, IS_HOLIDAY, HOLIDAY_DESCRIPTION, DOW_SIMPLE, MCI_CATEGORY) %>% 
   mutate(OCC_YEAR = OCC_YEAR - 2017) -> to_aggregate
to_aggregate
```

```{r}
sqldf("
      SELECT OCC_YEAR, OCC_MONTH_NUM, OCC_DAY, OCC_HOUR, OCC_DOY, OCC_DOW,
      DIVISION, PREMISES_TYPE, UCR_CODE_CATEGORY, OFFENCE_REWORK,
      NEIGHBOURHOOD_158, IS_HOLIDAY, HOLIDAY_DESCRIPTION, DOW_SIMPLE,
      MCI_CATEGORY, COUNT(DISTINCT EVENT_UNIQUE_ID) NUM_CRIMES
      FROM to_aggregate
      GROUP BY OCC_YEAR, OCC_MONTH_NUM, OCC_DAY, OCC_HOUR, OCC_DOY, OCC_DOW,
      DIVISION, PREMISES_TYPE, UCR_CODE_CATEGORY, OFFENCE_REWORK,
      NEIGHBOURHOOD_158, IS_HOLIDAY, HOLIDAY_DESCRIPTION, DOW_SIMPLE,
      MCI_CATEGORY
      ") %>% 
   mutate(COVID_ERA = ifelse(OCC_YEAR < 3, "PRE-COVID",
                             ifelse(OCC_YEAR < 5, "COVID", "POST-COVID"))) %>% 
   select(OCC_YEAR:DOW_SIMPLE, COVID_ERA, NUM_CRIMES) -> aggregated_count
aggregated_count
```

Writing this to a csv

```{r}
write.csv(aggregated_count, "mci_regression_setup.csv", row.names=FALSE, na="")
```

